export enum PaletteType {
  Indexed = 'Indexed',
  Mono = 'Monochrome',
  RGB = 'RGB',
  Mixer = 'Mixer',
  Auto = 'Auto',
}

export enum PaletteGroup {
  CGA2Bit = 'IBM CGA 2-bit modes',
  RetroPC = 'Retro PCs',
  RetroVC = 'Retro Consoles',
  Mono = 'Monochrome',
  Duo = 'Dual Tone',
  RGB = 'RGB',
  CMYK = 'CMYK',
  Auto = 'Optimized (Auto)',
  User = 'User (custom)',
  Other = 'Other',
  Generated = '__AUTOGENERATED',
  Hidden = '__HIDDEN',
}

export interface Palette {
  name: string;
  readonly type: PaletteType;
  readonly group: PaletteGroup;
  data: number[];
}
