import type { Directory } from './types';

const FS_ROOT: Directory = {
  class: 'dir',
  name: 'My Computer',
  created: 0,
  modified: 0,
  items: [
    {
      class: 'dir',
      name: 'Documents',
      created: 1687629014,
      modified: 1687629028,
      items: [
        {
          class: 'dir',
          name: 'Articles',
          created: 1687555586,
          modified: 1687629026,
          items: [
          ],
        },
        {
          class: 'dir',
          name: 'Photos',
          created: 1687555579,
          modified: 1687666863,
          items: [
            {
              class: 'dir',
              name: 'Budapest 2020',
              created: 1687662182,
              modified: 1687662241,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Avenue.jpg',
                  created: 1687662240,
                  modified: 1687666840,
                  size: 492830,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Bridge.jpg',
                  created: 1687662239,
                  modified: 1687666840,
                  size: 345745,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Danube.jpg',
                  created: 1687662239,
                  modified: 1687666839,
                  size: 419700,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Ferris Wheel.jpg',
                  created: 1687662240,
                  modified: 1687666841,
                  size: 478671,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Országház at night.jpg',
                  created: 1687662239,
                  modified: 1687666840,
                  size: 464790,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Országház daytime.jpg',
                  created: 1687662240,
                  modified: 1687666841,
                  size: 406067,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Taxi.jpg',
                  created: 1687662239,
                  modified: 1687666839,
                  size: 480253,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Train.jpg',
                  created: 1687662238,
                  modified: 1687666839,
                  size: 427718,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Tram.jpg',
                  created: 1687662241,
                  modified: 1687666841,
                  size: 516914,
                },
              ],
            },
            {
              class: 'dir',
              name: 'France 2023',
              created: 1687666841,
              modified: 1687666845,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Arc de Triomphe.jpg',
                  created: 1687666844,
                  modified: 1687666844,
                  size: 634600,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Architecture 1.jpg',
                  created: 1687666843,
                  modified: 1687666843,
                  size: 442179,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Architecture 2.jpg',
                  created: 1687666842,
                  modified: 1687666842,
                  size: 614154,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Metz church.jpg',
                  created: 1687666845,
                  modified: 1687666845,
                  size: 356406,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Mirror.jpg',
                  created: 1687666843,
                  modified: 1687666843,
                  size: 607376,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Pantheon.jpg',
                  created: 1687666844,
                  modified: 1687666844,
                  size: 532539,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Paris corner.jpg',
                  created: 1687666844,
                  modified: 1687666845,
                  size: 560612,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Paris skyline.jpg',
                  created: 1687666844,
                  modified: 1687666844,
                  size: 188153,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Paris street.jpg',
                  created: 1687666842,
                  modified: 1687666842,
                  size: 487136,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Sacre Coeur 1.jpg',
                  created: 1687666842,
                  modified: 1687666842,
                  size: 439273,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Sacre Coeur 2.jpg',
                  created: 1687666841,
                  modified: 1687666841,
                  size: 497368,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Statue.jpg',
                  created: 1687666843,
                  modified: 1687666843,
                  size: 222784,
                },
              ],
            },
            {
              class: 'dir',
              name: 'Ireland 2020',
              created: 1687666845,
              modified: 1687666848,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Boat.jpg',
                  created: 1687666846,
                  modified: 1687666846,
                  size: 403497,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Calm.jpg',
                  created: 1687666848,
                  modified: 1687666848,
                  size: 210472,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Deer.jpg',
                  created: 1687666846,
                  modified: 1687666846,
                  size: 234861,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Ferrari.jpg',
                  created: 1687666847,
                  modified: 1687666847,
                  size: 372775,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Field.jpg',
                  created: 1687666846,
                  modified: 1687666846,
                  size: 530752,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Plane wing.jpg',
                  created: 1687666848,
                  modified: 1687666848,
                  size: 180734,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Road.jpg',
                  created: 1687666846,
                  modified: 1687666846,
                  size: 297438,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Robin.jpg',
                  created: 1687666845,
                  modified: 1687666845,
                  size: 227766,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Rock pillars.jpg',
                  created: 1687666847,
                  modified: 1687666847,
                  size: 729785,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Stone.jpg',
                  created: 1687666847,
                  modified: 1687666847,
                  size: 514995,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Sunset.jpg',
                  created: 1687666848,
                  modified: 1687666848,
                  size: 266529,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Trail.jpg',
                  created: 1687666845,
                  modified: 1687666845,
                  size: 271732,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Wave.jpg',
                  created: 1687666848,
                  modified: 1687666848,
                  size: 619685,
                },
              ],
            },
            {
              class: 'dir',
              name: 'Japan 2023',
              created: 1687666848,
              modified: 1687666858,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Akihabara 1.jpg',
                  created: 1687666854,
                  modified: 1687666854,
                  size: 584365,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Akihabara 2.jpg',
                  created: 1687666854,
                  modified: 1687666854,
                  size: 578959,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Bridge.jpg',
                  created: 1687666852,
                  modified: 1687666852,
                  size: 888843,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Forest.jpg',
                  created: 1687666853,
                  modified: 1687666853,
                  size: 857771,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fuji houses.jpg',
                  created: 1687666850,
                  modified: 1687666850,
                  size: 434591,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fuji taxi.jpg',
                  created: 1687666853,
                  modified: 1687666853,
                  size: 325726,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fujisan sunset.jpg',
                  created: 1687666857,
                  modified: 1687666857,
                  size: 221868,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fujisan.jpg',
                  created: 1687666857,
                  modified: 1687666857,
                  size: 438602,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fushimi Inari 1.jpg',
                  created: 1687666849,
                  modified: 1687666849,
                  size: 473703,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Fushimi Inari 2.jpg',
                  created: 1687666849,
                  modified: 1687666849,
                  size: 463697,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Ginkaku-ji gardens.jpg',
                  created: 1687666851,
                  modified: 1687666851,
                  size: 761228,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Ginza highway.jpg',
                  created: 1687666855,
                  modified: 1687666855,
                  size: 490297,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Ginza skyline.jpg',
                  created: 1687666853,
                  modified: 1687666853,
                  size: 437966,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kinkaku-ji.jpg',
                  created: 1687666856,
                  modified: 1687666856,
                  size: 461839,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kurama 1.jpg',
                  created: 1687666849,
                  modified: 1687666849,
                  size: 799310,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kurama 2.jpg',
                  created: 1687666850,
                  modified: 1687666850,
                  size: 825312,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kurama path.jpg',
                  created: 1687666856,
                  modified: 1687666856,
                  size: 885146,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kurama steps.jpg',
                  created: 1687666856,
                  modified: 1687666856,
                  size: 894492,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Kyoto from above.jpg',
                  created: 1687666851,
                  modified: 1687666851,
                  size: 563824,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Nara deer 1.jpg',
                  created: 1687666852,
                  modified: 1687666852,
                  size: 385125,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Nara deer 2.jpg',
                  created: 1687666852,
                  modified: 1687666852,
                  size: 467285,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Otaimatsu 1.jpg',
                  created: 1687666852,
                  modified: 1687666852,
                  size: 329416,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Otaimatsu 2.jpg',
                  created: 1687666851,
                  modified: 1687666851,
                  size: 303874,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Roots.jpg',
                  created: 1687666858,
                  modified: 1687666858,
                  size: 817877,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Shibuya.jpg',
                  created: 1687666850,
                  modified: 1687666850,
                  size: 577250,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Shiisaa.jpg',
                  created: 1687666856,
                  modified: 1687666856,
                  size: 380480,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Shirait0-no-taki 2.jpg',
                  created: 1687666855,
                  modified: 1687666855,
                  size: 629138,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Shiraito-no-taki 1.jpg',
                  created: 1687666858,
                  modified: 1687666858,
                  size: 797765,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Shiraito-no-taki 3.jpg',
                  created: 1687666857,
                  modified: 1687666857,
                  size: 704084,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Taxi.jpg',
                  created: 1687666850,
                  modified: 1687666850,
                  size: 562198,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Temple cat.jpg',
                  created: 1687666854,
                  modified: 1687666854,
                  size: 331402,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Tokyo Skytree 1.jpg',
                  created: 1687666854,
                  modified: 1687666854,
                  size: 301617,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Tokyo Skytree 2.jpg',
                  created: 1687666853,
                  modified: 1687666853,
                  size: 443856,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Tokyo sunset.jpg',
                  created: 1687666858,
                  modified: 1687666858,
                  size: 237112,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Winding path.jpg',
                  created: 1687666855,
                  modified: 1687666855,
                  size: 779865,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'monch.jpg',
                  created: 1687666857,
                  modified: 1687666857,
                  size: 393446,
                },
              ],
            },
            {
              class: 'dir',
              name: 'London 2020',
              created: 1687662183,
              modified: 1687666858,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Aston Martin.jpg',
                  created: 1687662241,
                  modified: 1687666859,
                  size: 533702,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Black cab.jpg',
                  created: 1687662242,
                  modified: 1687666860,
                  size: 532282,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Graffiti.jpg',
                  created: 1687666858,
                  modified: 1687666858,
                  size: 480812,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'The Shard.jpg',
                  created: 1687662242,
                  modified: 1687666859,
                  size: 299621,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Yellow Corvette.jpg',
                  created: 1687662241,
                  modified: 1687666859,
                  size: 386073,
                },
              ],
            },
            {
              class: 'dir',
              name: 'Netherlands 2023',
              created: 1687666860,
              modified: 1687666863,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Amsterdam bikes.jpg',
                  created: 1687666860,
                  modified: 1687666860,
                  size: 265144,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Amsterdam buildings.jpg',
                  created: 1687666861,
                  modified: 1687666861,
                  size: 711850,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Amsterdam canal 1.jpg',
                  created: 1687666862,
                  modified: 1687666862,
                  size: 811257,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Amsterdam canal 2.jpg',
                  created: 1687666863,
                  modified: 1687666863,
                  size: 772389,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Amsterdam tram.jpg',
                  created: 1687666860,
                  modified: 1687666860,
                  size: 499663,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Delft 1.jpg',
                  created: 1687666862,
                  modified: 1687666862,
                  size: 637348,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Delft 2.jpg',
                  created: 1687666863,
                  modified: 1687666863,
                  size: 765326,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Delft at night.jpg',
                  created: 1687666861,
                  modified: 1687666861,
                  size: 476580,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Delft canal.jpg',
                  created: 1687666862,
                  modified: 1687666862,
                  size: 648515,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Edam 1.jpg',
                  created: 1687666860,
                  modified: 1687666860,
                  size: 843453,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Edam 2.jpg',
                  created: 1687666861,
                  modified: 1687666861,
                  size: 643556,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Edam boats.jpg',
                  created: 1687666862,
                  modified: 1687666862,
                  size: 605363,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Edam cat.jpg',
                  created: 1687666863,
                  modified: 1687666863,
                  size: 583139,
                },
              ],
            },
            {
              class: 'dir',
              name: 'Patagonia 2022',
              created: 1687666863,
              modified: 1687666867,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'Beach.jpg',
                  created: 1687666865,
                  modified: 1687666865,
                  size: 626319,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Big lake.jpg',
                  created: 1687666867,
                  modified: 1687666867,
                  size: 334658,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Boat 1.jpg',
                  created: 1687666864,
                  modified: 1687666864,
                  size: 461183,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Boat 2.jpg',
                  created: 1687666864,
                  modified: 1687666864,
                  size: 595439,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Forest trail.jpg',
                  created: 1687666865,
                  modified: 1687666866,
                  size: 709315,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Layers.jpg',
                  created: 1687666863,
                  modified: 1687666864,
                  size: 290870,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Old car.jpg',
                  created: 1687666865,
                  modified: 1687666865,
                  size: 617002,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Orange flower.jpg',
                  created: 1687666866,
                  modified: 1687666866,
                  size: 174049,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Peaks.jpg',
                  created: 1687666865,
                  modified: 1687666865,
                  size: 390793,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Pier.jpg',
                  created: 1687666866,
                  modified: 1687666867,
                  size: 417811,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Riverside trail.jpg',
                  created: 1687666866,
                  modified: 1687666866,
                  size: 711470,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Road.jpg',
                  created: 1687666864,
                  modified: 1687666864,
                  size: 683075,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Sailboat.jpg',
                  created: 1687666864,
                  modified: 1687666864,
                  size: 499193,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Sunset over lake.jpg',
                  created: 1687666867,
                  modified: 1687666867,
                  size: 317132,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Towers.jpg',
                  created: 1687666867,
                  modified: 1687666867,
                  size: 745844,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Wave.jpg',
                  created: 1687666866,
                  modified: 1687666866,
                  size: 417501,
                },
              ],
            },
          ],
        },
        {
          class: 'dir',
          name: 'Projects',
          created: 1687555568,
          modified: 1687958010,
          items: [
            {
              class: 'dir',
              name: 'screenshots',
              created: 1687670892,
              modified: 1687957820,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'DitherOS.png',
                  created: 1687670914,
                  modified: 1687670914,
                  size: 191872,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'DitherOS.webp',
                  created: 1687670914,
                  modified: 1687670914,
                  size: 128856,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Lab.jpg',
                  created: 1687957700,
                  modified: 1687957807,
                  size: 149394,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'Lab.webp',
                  created: 1687957714,
                  modified: 1687957785,
                  size: 90844,
                },
              ],
            },
            {
              class: 'file',
              type: 'md',
              name: 'DitherOS.md',
              created: 1687818279,
              modified: 1687818279,
              size: 2585,
            },
            {
              class: 'file',
              type: 'md',
              name: 'Recipes App.md',
              created: 1687493346,
              modified: 1687675940,
              size: 2503,
            },
            {
              class: 'file',
              type: 'md',
              name: 'UI Lab.md',
              created: 1687958010,
              modified: 1687960119,
              size: 578,
            },
          ],
        },
        {
          class: 'file',
          type: 'md',
          name: 'test.md',
          created: 1687489101,
          modified: 1687496152,
          size: 1127,
        },
      ],
    },
    {
      class: 'dir',
      name: 'system',
      created: 1687629033,
      modified: 1687638043,
      items: [
        {
          class: 'dir',
          name: 'Applications',
          created: 1687629318,
          modified: 1688014384,
          items: [
            {
              class: 'dir',
              name: 'about',
              created: 1687638222,
              modified: 1687657819,
              items: [
                {
                  class: 'file',
                  type: 'app',
                  name: 'about.app',
                  created: 1687656646,
                  modified: 1687656646,
                  size: 0,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687446185,
                  modified: 1687446185,
                  size: 385,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687657802,
                  modified: 1687657802,
                  size: 470,
                },
              ],
            },
            {
              class: 'dir',
              name: 'files',
              created: 1687638230,
              modified: 1687656651,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687639488,
                  modified: 1687639666,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'go-up.png',
                      created: 1687548122,
                      modified: 1687548122,
                      size: 362,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'files.app',
                  created: 1687656651,
                  modified: 1687656651,
                  size: 0,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687494053,
                  modified: 1687494053,
                  size: 438,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687494119,
                  modified: 1687494119,
                  size: 608,
                },
              ],
            },
            {
              class: 'dir',
              name: 'intro',
              created: 1687629331,
              modified: 1688018646,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687657872,
                  modified: 1688018982,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'me copy.png',
                      created: 1688018968,
                      modified: 1688018968,
                      size: 28089,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'me.png',
                      created: 1687449488,
                      modified: 1688018982,
                      size: 20119,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687448181,
                  modified: 1687448181,
                  size: 439,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687657822,
                  modified: 1687657822,
                  size: 625,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'intro.app',
                  created: 1687656656,
                  modified: 1687656656,
                  size: 0,
                },
              ],
            },
            {
              class: 'dir',
              name: 'mine',
              created: 1687638268,
              modified: 1687656863,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687412241,
                  modified: 1687412241,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'flag-question.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1927,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'flag.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1927,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'mine.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1953,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num-minus.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1472,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num0.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 178,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num1.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 144,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num2.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 178,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num3.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 168,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num4.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 179,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num5.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 181,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num6.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 184,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num7.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 155,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num8.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 176,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'num9.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 183,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'smiley-click.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 258,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'smiley-dead.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 242,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'smiley-win.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1574,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'smiley.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 227,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'wrong.png',
                      created: 1687412241,
                      modified: 1687412241,
                      size: 1952,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687441743,
                  modified: 1687441743,
                  size: 382,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687441743,
                  modified: 1687441743,
                  size: 532,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'mine.app',
                  created: 1687656662,
                  modified: 1687656662,
                  size: 0,
                },
              ],
            },
            {
              class: 'dir',
              name: 'preview',
              created: 1687638244,
              modified: 1687656670,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687639785,
                  modified: 1687639788,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'zoom-in.png',
                      created: 1687588570,
                      modified: 1687588570,
                      size: 305,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'zoom-out.png',
                      created: 1687588580,
                      modified: 1687588580,
                      size: 286,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687494418,
                  modified: 1687494418,
                  size: 457,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687494425,
                  modified: 1687494425,
                  size: 586,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'preview.app',
                  created: 1687656670,
                  modified: 1687656670,
                  size: 0,
                },
              ],
            },
            {
              class: 'dir',
              name: 'solitaire',
              created: 1687874324,
              modified: 1687874324,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687874324,
                  modified: 1687903606,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back0.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1196,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back1.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1238,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back10.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1895,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back11.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1729,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back2.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1720,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back3.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1768,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back4.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 2178,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back5.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 2312,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back6.gif',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 2158,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back6.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1630,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back7.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 2247,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back8.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 2397,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back9.gif',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1932,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'back9.png',
                      created: 1687903606,
                      modified: 1687903606,
                      size: 1483,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-1.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 680,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-10.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 881,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-11.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1203,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-12.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1313,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-13.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1148,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-2.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 726,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-3.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 769,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-4.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 738,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-5.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 805,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-6.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 768,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-7.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 804,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-8.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 813,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-clubs-9.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 870,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-1.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 546,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-10.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 672,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-11.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1148,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-12.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1278,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-13.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1242,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-2.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 572,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-3.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 604,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-4.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 590,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-5.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 628,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-6.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 614,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-7.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 632,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-8.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 658,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-diamonds-9.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 660,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-frame.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 432,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-1.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 559,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-10.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 715,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-11.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1191,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-12.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1298,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-13.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1321,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-2.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 588,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-3.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 626,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-4.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 602,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-5.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 656,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-6.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 646,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-7.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 671,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-8.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 653,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-hearts-9.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 700,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-1.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 906,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-10.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 922,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-11.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1174,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-12.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1252,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-13.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 1165,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-2.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 725,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-3.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 782,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-4.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 755,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-5.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 817,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-6.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 793,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-7.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 827,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-8.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 843,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'card-spades-9.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 899,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'deck-empty.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 550,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'stack-empty.png',
                      created: 1687874324,
                      modified: 1687874324,
                      size: 544,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687874324,
                  modified: 1687874324,
                  size: 359,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687874324,
                  modified: 1687874324,
                  size: 421,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'solitaire.app',
                  created: 1687874324,
                  modified: 1687874324,
                  size: 0,
                },
              ],
            },
            {
              class: 'dir',
              name: 'sudoku',
              created: 1687729478,
              modified: 1687753130,
              items: [
                {
                  class: 'dir',
                  name: 'resources',
                  created: 1687753130,
                  modified: 1687757349,
                  items: [
                    {
                      class: 'file',
                      type: 'md',
                      name: 'help.md',
                      created: 1687757349,
                      modified: 1687757643,
                      size: 370,
                    },
                    {
                      class: 'file',
                      type: 'file',
                      name: 'sudoku_easy.json',
                      created: 1687750618,
                      modified: 1687754566,
                      size: 383870,
                    },
                    {
                      class: 'file',
                      type: 'file',
                      name: 'sudoku_hard.json',
                      created: 1687749214,
                      modified: 1687749214,
                      size: 383869,
                    },
                    {
                      class: 'file',
                      type: 'file',
                      name: 'sudoku_medium.json',
                      created: 1687741657,
                      modified: 1687745187,
                      size: 383869,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1687729515,
                  modified: 1687729515,
                  size: 375,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1687729515,
                  modified: 1687729515,
                  size: 763,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'sudoku.app',
                  created: 1687729491,
                  modified: 1687729491,
                  size: 0,
                },
              ],
            },
            {
              class: 'dir',
              name: 'theme',
              created: 1688014384,
              modified: 1688014538,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_16.png',
                  created: 1688014512,
                  modified: 1688014512,
                  size: 450,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'icon_32.png',
                  created: 1688014535,
                  modified: 1688014535,
                  size: 673,
                },
                {
                  class: 'file',
                  type: 'app',
                  name: 'theme.app',
                  created: 1688014390,
                  modified: 1688014390,
                  size: 0,
                },
              ],
            },
          ],
        },
        {
          class: 'dir',
          name: 'Resources',
          created: 1687638043,
          modified: 1687725238,
          items: [
            {
              class: 'dir',
              name: 'Icons',
              created: 1687638059,
              modified: 1687724554,
              items: [
                {
                  class: 'dir',
                  name: 'FileType',
                  created: 1687548703,
                  modified: 1687657265,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'app_16.png',
                      created: 1687441915,
                      modified: 1687441915,
                      size: 336,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'app_32.png',
                      created: 1687441888,
                      modified: 1687441888,
                      size: 353,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'dir_16.png',
                      created: 1687546080,
                      modified: 1687546080,
                      size: 378,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'dir_32.png',
                      created: 1687546064,
                      modified: 1687546064,
                      size: 489,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'file_16.png',
                      created: 1687657151,
                      modified: 1687657265,
                      size: 2214,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'file_32.png',
                      created: 1687657124,
                      modified: 1687657255,
                      size: 2232,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'image_16.png',
                      created: 1687549280,
                      modified: 1687549280,
                      size: 399,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'image_32.png',
                      created: 1687549269,
                      modified: 1687549269,
                      size: 515,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'md_16.png',
                      created: 1687581188,
                      modified: 1687581188,
                      size: 382,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'md_32.png',
                      created: 1687581176,
                      modified: 1687581176,
                      size: 451,
                    },
                  ],
                },
                {
                  class: 'dir',
                  name: 'Start',
                  created: 1687720317,
                  modified: 1688014710,
                  items: [
                    {
                      class: 'file',
                      type: 'image',
                      name: 'applications.png',
                      created: 1687720647,
                      modified: 1687720647,
                      size: 512,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'documents.png',
                      created: 1687720714,
                      modified: 1687720714,
                      size: 496,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'favorites.png',
                      created: 1688014693,
                      modified: 1688014693,
                      size: 450,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'help.png',
                      created: 1687722716,
                      modified: 1687722716,
                      size: 553,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'settings.png',
                      created: 1687722788,
                      modified: 1687722788,
                      size: 572,
                    },
                    {
                      class: 'file',
                      type: 'image',
                      name: 'shutdown.png',
                      created: 1687723028,
                      modified: 1687723028,
                      size: 546,
                    },
                  ],
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'shutdown.png',
                  created: 1687724532,
                  modified: 1687724532,
                  size: 495,
                },
              ],
            },
            {
              class: 'dir',
              name: 'UI',
              created: 1687638461,
              modified: 1687674052,
              items: [
                {
                  class: 'file',
                  type: 'image',
                  name: 'check.c.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 123,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'check.c.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1453,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'check.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 83,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'check.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1416,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'close.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 2086,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'close.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 3711,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'copy.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1977,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'delete.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 347,
                },
                {
                  class: 'file',
                  type: 'file',
                  name: 'dot.svg',
                  created: 1687674052,
                  modified: 1687674200,
                  size: 156,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'max.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 2063,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'max.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 3685,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'min.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 2032,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'min.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 3673,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'minus.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1638,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'new.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1666,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'plus.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1648,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'remove.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 1691,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'restore.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 2125,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'restore.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 3810,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'save.png',
                  created: 1687441743,
                  modified: 1687441743,
                  size: 165,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrolldown.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 131,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrolldown.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 105,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollleft.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 128,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollleft.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 125,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollright.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 137,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollright.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 122,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollup.d.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 126,
                },
                {
                  class: 'file',
                  type: 'image',
                  name: 'scrollup.png',
                  created: 1687412241,
                  modified: 1687412241,
                  size: 117,
                },
              ],
            },
            {
              class: 'file',
              type: 'image',
              name: 'shutdown.png',
              created: 1687725215,
              modified: 1687725215,
              size: 4604,
            },
          ],
        },
      ],
    },
  ],
};

export default FS_ROOT;
