import { useEffect, useMemo } from 'react';

import { useAppState } from '@/components/desktop/Window/context';
import { useAppSettings } from '@/hooks/use-app-settings';

import { generatePalette } from '../dither/paletteGen/PaletteGenerator';
import palettes from '../dither/palettes';
import {
  type Palette,
  PaletteGroup,
  PaletteType,
} from '../dither/palettes/types';
import Win4bRGBI from '../dither/palettes/Win4bRGBI';
import useImage from './use-image';
import { openFile } from '@/utils/file';

export default function usePalettes(rt: HTMLCanvasElement | null) {
  const [state, update] = useAppState('dither');
  const [settings, set] = useAppSettings('dither');
  const image = useImage();

  const allPalettes = useMemo(
    () => [...palettes, ...settings.customPalettes],
    [settings.customPalettes],
  );

  const readPalettes = (el: HTMLImageElement) => {
    const offscreen = new OffscreenCanvas(el.naturalWidth, el.naturalHeight);
    const ctx = offscreen.getContext('2d');
    if (!ctx) return;

    ctx.drawImage(el, 0, 0);
    const data = ctx.getImageData(0, 0, offscreen.width, offscreen.height);

    const newPalettes: Palette[] = [];
    for (let i = 0; i < data.height; i++) {
      const rowIdx = i * data.width * 4;
      let j = 0;
      let name = '';
      const pdata: number[] = [];

      // Parse palette name
      while (data.data[rowIdx + j * 4 + 3] != 0) {
        name += String.fromCharCode(data.data[rowIdx + j * 4]);
        j++;
      }
      name = name.trim();
      if (newPalettes.some((pal) => pal.name === name)) {
        console.warn(`DitherLab: duplicate palette name ${name}, skipped`);
        continue;
      }
      j++;

      // Parse palette data
      while (data.data[rowIdx + j * 4 + 3] != 0) {
        pdata.push(data.data[rowIdx + j * 4 + 0]);
        pdata.push(data.data[rowIdx + j * 4 + 1]);
        pdata.push(data.data[rowIdx + j * 4 + 2]);
        j++;
      }

      // Create palette
      newPalettes.push({
        name,
        type: PaletteType.Indexed,
        group: PaletteGroup.User,
        data: pdata,
      });
    }

    set({ customPalettes: [...settings.customPalettes, ...newPalettes] });
    if (newPalettes.length > 0)
      update({ paletteGroup: PaletteGroup.User, palette: newPalettes[0] });
  };

  const upload = async () => {
    const file = await openFile(['image/png', 'image/jpeg', 'image/webp']);
    if (file) {
      const reader = new FileReader();

      reader.addEventListener(
        'load',
        () => {
          const el = document.createElement('img');
          el.src = reader.result as string;
          el.addEventListener('load', () => {
            readPalettes(el);
            el.remove();
          });
          document.body.appendChild(el);
        },
        { once: true },
      );
      reader.readAsDataURL(file);
    }
  };

  const clear = () => {
    set({ customPalettes: [] });
    if (state.paletteGroup === PaletteGroup.User)
      update({
        paletteGroup: PaletteGroup.RetroPC,
        palette: Win4bRGBI,
        paletteName: Win4bRGBI.name,
      });
  };

  useEffect(() => {
    console.log(state.paletteName);
    const palette = allPalettes.find((pal) => pal.name === state.paletteName);
    if (!palette) return;

    console.log(palette);

    // If the palette is not autogenerated, just set it as active
    if (palette.type !== PaletteType.Auto) update({ palette });
    // For auto palettes, generate a palette from the image
    else if (image) {
      const generate = async () => {
        const temp = document.createElement('canvas');
        const ctx = temp.getContext('2d');
        if (!ctx) return;

        temp.width = rt?.width ?? 0;
        temp.height = rt?.height ?? 0;
        const bmp = await createImageBitmap(new Blob([image.data]));
        ctx.drawImage(bmp, 0, 0, temp.width, temp.height);
        const data = ctx.getImageData(0, 0, temp.width, temp.height);

        const generated = generatePalette(
          {
            size: palette.data[0],
            reservedLevel: palette.data[1],
            levels: palette.data[2],
            thresholdCoeff: palette.data[3],
          },
          data,
        );

        update({ palette: generated });
      };

      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [allPalettes, rt, state.paletteName]);

  return { palettes: allPalettes, upload, clear };
}
