import cn from 'classnames';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { useAppState, useWindow } from '@/components/desktop/Window/context';
import Button from '@/components/ui/Button';
import Menu from '@/components/ui/Menu';
import ScrollContainer from '@/components/ui/ScrollContainer';
import { Toolbar } from '@/components/ui/Toolbar';
import palettes from '@/components/apps/dither-lab/dither/palettes';
import {
  type Palette,
  PaletteGroup,
  PaletteType,
} from '@/components/apps/dither-lab/dither/palettes/types';
import Win4bRGBI from '@/components/apps/dither-lab/dither/palettes/Win4bRGBI';
import { useAppSettings } from '@/hooks/use-app-settings';
import ZoomControls from '@/components/ui/zoom-controls';
import useZoom from '@/hooks/use-zoom';

import DitherLabImageInfo from './panels/dither-lab-image-info';
import DitherLabPaletteEditor from './panels/dither-lab-palette-editor';
import DitherLabPaletteSelect from './panels/dither-lab-palette-select';
import DitherLabRenderOptions from './panels/dither-lab-render-options';
import DitherLabResizeOptions from './panels/dither-lab-resize-options';
import GlRenderer from './renderers/gl-renderer';
import SoftwareRenderer from './renderers/software-renderer';
import { DitherLabDevice, DitherLabSettings } from './types';
import useImageUploader from './utils/use-image-uploader';
import useImage from './utils/use-image';
import { generatePalette } from './dither/paletteGen/PaletteGenerator';

const ZOOM_STOPS = [1, 1.5, 2, 3, 4, 6, 8, 16, 32, 64];

export default function DitherLab() {
  const { close } = useWindow();
  const [state, update] = useAppState('dither');
  const [settings, set] = useAppSettings('dither');
  const image = useImage();

  const hiddenInputRef = useRef<HTMLInputElement>(null);
  const importHiddenInputRef = useRef<HTMLInputElement>(null);
  const viewportRef = useRef<HTMLDivElement>(null);

  const [rt, setRt] = useState<HTMLCanvasElement | null>(null);

  const [status, setStatus] = useState<'ready' | 'rendering' | 'done'>('ready');
  const [renderTime, setRenderTime] = useState(0);

  /*
   * Image loading
   */
  const { uploadHandler, open } = useImageUploader();
  const upload = () => hiddenInputRef.current?.click();

  /*
   * Palette selection and generation
   */
  const allPalettes = useMemo(
    () => [...palettes, ...settings.customPalettes],
    [settings.customPalettes],
  );

  useEffect(() => {
    console.log(state.paletteName);
    const palette = allPalettes.find((pal) => pal.name === state.paletteName);
    if (!palette) return;

    console.log(palette);

    // If the palette is not autogenerated, just set it as active
    if (palette.type !== PaletteType.Auto) update({ palette });
    // For auto palettes, generate a palette from the image
    else if (image) {
      const generate = async () => {
        const temp = document.createElement('canvas');
        const ctx = temp.getContext('2d');
        if (!ctx) return;

        temp.width = rt?.width ?? 0;
        temp.height = rt?.height ?? 0;
        const bmp = await createImageBitmap(new Blob([image.data]));
        ctx.drawImage(bmp, 0, 0, temp.width, temp.height);
        const data = ctx.getImageData(0, 0, temp.width, temp.height);

        const generated = generatePalette(
          {
            size: palette.data[0],
            reservedLevel: palette.data[1],
            levels: palette.data[2],
            thresholdCoeff: palette.data[3],
          },
          data,
        );

        update({ palette: generated });
      };

      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [allPalettes, rt, state.paletteName]);

  /*
   * Output saving
   */
  const download = () => {
    if (!rt || !image) return;
    const dataUrl = rt
      .toDataURL('image/png')
      .replace('image/png', 'image/octet-stream');

    let filename = image.meta.filename.split('.').slice(0, -1).join('.');

    filename = `${filename} - ${state.palette.name}.png`;

    const link = document.createElement('a');
    link.setAttribute('download', filename);
    link.setAttribute('href', dataUrl);
    link.click();
  };

  /*
   * View
   */
  const setZoom = useCallback((zoom: number) => update({ zoom }), [update]);
  const zoom = useZoom(
    state.zoom,
    setZoom,
    viewportRef,
    undefined,
    ZOOM_STOPS,
    rt,
  );

  /*
   * Palette import
   */
  const readPalettes = (el: HTMLImageElement) => {
    const offscreen = new OffscreenCanvas(el.naturalWidth, el.naturalHeight);
    const ctx = offscreen.getContext('2d');
    if (!ctx) return;

    ctx.drawImage(el, 0, 0);
    const data = ctx.getImageData(0, 0, offscreen.width, offscreen.height);

    const newPalettes: Palette[] = [];
    for (let i = 0; i < data.height; i++) {
      const rowIdx = i * data.width * 4;
      let j = 0;
      let name = '';
      const pdata: number[] = [];

      // Parse palette name
      while (data.data[rowIdx + j * 4 + 3] != 0) {
        name += String.fromCharCode(data.data[rowIdx + j * 4]);
        j++;
      }
      name = name.trim();
      if (newPalettes.some((pal) => pal.name === name)) {
        console.warn(`DitherLab: duplicate palette name ${name}, skipped`);
        continue;
      }
      j++;

      // Parse palette data
      while (data.data[rowIdx + j * 4 + 3] != 0) {
        pdata.push(data.data[rowIdx + j * 4 + 0]);
        pdata.push(data.data[rowIdx + j * 4 + 1]);
        pdata.push(data.data[rowIdx + j * 4 + 2]);
        j++;
      }

      // Create palette
      newPalettes.push({
        name,
        type: PaletteType.Indexed,
        group: PaletteGroup.User,
        data: pdata,
      });
    }

    set({ customPalettes: [...settings.customPalettes, ...newPalettes] });
    if (newPalettes.length > 0)
      update({ paletteGroup: PaletteGroup.User, palette: newPalettes[0] });
  };

  const importPaletteFromImage = (ev: React.ChangeEvent<HTMLInputElement>) => {
    const input = ev.target;
    if (input?.files) {
      const file = input.files[0];
      const reader = new FileReader();

      reader.addEventListener(
        'load',
        () => {
          const el = document.createElement('img');
          el.src = reader.result as string;
          el.addEventListener('load', () => {
            readPalettes(el);
            el.remove();
          });
          document.body.appendChild(el);
        },
        { once: true },
      );
      reader.readAsDataURL(file);
    }
  };

  const importPalettes = () => importHiddenInputRef.current?.click();

  const clearPalettes = () => {
    set({ customPalettes: [] });
    if (state.paletteGroup === PaletteGroup.User)
      update({
        paletteGroup: PaletteGroup.RetroPC,
        palette: Win4bRGBI,
        paletteName: Win4bRGBI.name,
      });
  };

  /*
   * UI
   */
  const Renderer = useMemo(
    () => (state.device === DitherLabDevice.GL ? GlRenderer : SoftwareRenderer),
    [state.device],
  );

  return (
    <div className="flex flex-col gap-0.5 min-w-0 select-none">
      <input
        type="file"
        className="hidden"
        ref={hiddenInputRef}
        onChange={uploadHandler}
      />
      <input
        type="file"
        className="hidden"
        ref={importHiddenInputRef}
        onChange={importPaletteFromImage}
      />

      <Menu.Bar>
        <Menu.Menu trigger={<Menu.Trigger>File</Menu.Trigger>}>
          <Menu.Item label="Upload..." onSelect={upload} />
          <Menu.Item label="Open..." onSelect={open} />
          <Menu.Item label="Save" onSelect={download} />

          <Menu.Separator />

          <Menu.Item label="Exit" onSelect={close} />
        </Menu.Menu>

        <Menu.Menu trigger={<Menu.Trigger>View</Menu.Trigger>}>
          <Menu.Sub label="Zoom">
            <Menu.RadioGroup
              value={state.zoom.toString()}
              onValueChange={(value) => setZoom(Number(value))}
            >
              <Menu.RadioItem value="1" label="100%" />
              <Menu.RadioItem value="2" label="200%" />
              <Menu.RadioItem value="3" label="300%" />
              <Menu.RadioItem value="4" label="400%" />
              <Menu.RadioItem value="6" label="600%" />
              <Menu.RadioItem value="8" label="800%" />
            </Menu.RadioGroup>

            <Menu.Separator />

            <Menu.Item
              label="Zoom to fit"
              onSelect={() => zoom.zoomTo('fit')}
            />
            <Menu.Item
              label="Zoom to fill"
              onSelect={() => zoom.zoomTo('fill')}
            />
          </Menu.Sub>

          <Menu.Separator />

          <Menu.CheckboxItem
            label="Status Bar"
            checked={settings.showStatusBar}
            onCheckedChange={(checked) => set({ showStatusBar: checked })}
          />
          <Menu.CheckboxItem
            label="Palette Editor"
            checked={settings.showPaletteEditor}
            onCheckedChange={(checked) => set({ showPaletteEditor: checked })}
          />
          <Menu.Sub label="Tool Panels">
            <Menu.RadioGroup
              value={settings.panelSide}
              onValueChange={(value) =>
                set({ panelSide: value as DitherLabSettings['panelSide'] })
              }
            >
              <Menu.RadioItem label="Left" value="left" />
              <Menu.RadioItem label="Right" value="right" />
            </Menu.RadioGroup>
          </Menu.Sub>
        </Menu.Menu>

        <Menu.Menu trigger={<Menu.Trigger>Palettes</Menu.Trigger>}>
          <Menu.Item label="Import..." onSelect={importPalettes} />

          <Menu.Separator />

          <Menu.Item label="Clear custom palettes" onSelect={clearPalettes} />
        </Menu.Menu>
      </Menu.Bar>

      <div
        className={cn('grow flex gap-0.5 min-h-0', {
          'flex-row': settings.panelSide === 'right',
          'flex-row-reverse': settings.panelSide === 'left',
        })}
      >
        <Renderer
          rt={rt}
          setRt={setRt}
          status={status}
          setStatus={setStatus}
          setRenderTime={setRenderTime}
          viewportRef={viewportRef}
          save={download}
        >
          <Toolbar className="grow">
            <Button variant="light" className="p-1" onClick={download}>
              <img src="fs/System Files/UI/save2.png" alt="Save" />
            </Button>
          </Toolbar>
          <Toolbar>
            <ZoomControls {...zoom} stops={ZOOM_STOPS} />
          </Toolbar>
        </Renderer>

        <div className="flex flex-row gap-0.5">
          <ScrollContainer hide="x" className="bg-surface w-58 min-w-58">
            <div className="flex flex-col w-54 min-w-54">
              <DitherLabImageInfo upload={upload} open={open} />
              <DitherLabResizeOptions />
              <DitherLabPaletteSelect
                openEditor={() => set({ showPaletteEditor: true })}
                importPalettes={importPalettes}
              />
              <DitherLabRenderOptions />
            </div>
          </ScrollContainer>

          {settings.showPaletteEditor ? (
            <DitherLabPaletteEditor
              close={() => set({ showPaletteEditor: false })}
            />
          ) : null}
        </div>
      </div>

      {settings.showStatusBar ? (
        <div className="flex flex-row gap-0.5">
          <div className="py-0.5 px-2 bevel-light-inset text-ellipsis whitespace-nowrap overflow-hidden flex-3">
            {status === 'done'
              ? `Done (${renderTime.toFixed(0)}ms)`
              : status === 'ready'
                ? 'Ready'
                : 'Rendering...'}
          </div>
          <div className="py-0.5 px-2 bevel-light-inset text-ellipsis whitespace-nowrap overflow-hidden flex-1">
            {image?.meta.filename ?? ''}
          </div>
          <div className="py-0.5 px-2 bevel-light-inset text-ellipsis whitespace-nowrap overflow-hidden flex-1">
            {state.renderWidth}x{state.renderHeight}
          </div>
          <div className="py-0.5 px-2 bevel-light-inset text-ellipsis whitespace-nowrap overflow-hidden flex-1">
            {state.palette.name}
          </div>
        </div>
      ) : null}
    </div>
  );
}
